### ISSUE TITLE
Readme on starting the storefront might be incorrect.

### ISSUE THREAD

**Issue by loktar00** [VirtoCommerce/vc-storefront#615]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version:  N/A
- Platform version:  Latest
- Storefront version:  Latest

### Expected behavior

The readme states to run `dotnet run` within the `vc-storefront` directory (or wherever you cloned the main repository).

### Actual behavior

Receive the error,

`Couldn't find a project to run. Ensure a project exists in c:\somepath\vc-storefront, or pass the path to the project using --project.`

### Steps to reproduce
1. Clone repository
2. cd to directory with cloned repository
3. Use the command `dotnet run`

### Potential fix

This however does work.

`dotnet run --project .\VirtoCommerce.Storefront\VirtoCommerce.Storefront.csproj`

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8125 has been created

**Comment by DanilBayushev** [comment]
Hello @loktar00 !
Thank you for your appeal!
The documentation will be updated shortly.

**Comment by trueboroda** [comment]
It was resolved in this pull request https://github.com/VirtoCommerce/vc-storefront/pull/617

**Comment by loktar00** [comment]
This still isn't resolved, you still have to specify a project,
